### ISSUE TITLE
Sightability Errors 2016

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_IDFG#8]
Placeholder to be edited...

**Comment by theangrycyclist** [comment]
We have three surveys in for 2016.  Salmon Elk, Beaverhead Elk, Mountain Valley Deer.

Salmon Elk will the sightability model runs
Beaverhead Elk data loads but sightability fails
Mountain Valley data loads but sightability fails

Not sure why?

**Comment by theangrycyclist** [comment]
![mvsetup](https://cloud.githubusercontent.com/assets/6676454/13504883/b882d2a0-e133-11e5-9a70-9f5eb28b459c.JPG)

**Comment by theangrycyclist** [comment]
![bhsetup](https://cloud.githubusercontent.com/assets/6676454/13505108/c99f602a-e134-11e5-8bd9-1a2273a2e57c.JPG)

**Comment by theangrycyclist** [comment]
One last thing.  Salmon results - top table - totals are quite a bit larger than the sum of the parts.

![salmonresults](https://cloud.githubusercontent.com/assets/6676454/13505308/db21cf44-e135-11e5-92ac-0fbbfe308e69.JPG)

**Comment by theangrycyclist** [comment]
Looks like island park elk fails too.

![islandparksetup](https://cloud.githubusercontent.com/assets/6676454/13580628/6429385e-e460-11e5-943c-500d21413667.JPG)

**Comment by Huh** [comment]
Ok, it looks like all of the units except Island park will run and produce results that don't seem outrageous.  The Hiller 12E Snow model has big CI's no matter what zone I choose.  Anyway, I think I know the problem with Island Park and will get to it in the morning.  In short, if only one stratum is surveyed and it is the third then it causes indexing problems.

**Comment by Huh** [comment]
Site updated and all units now run.  I will suggest closing this issue as other issues are about to be posted reflecting what needs to be done.
